
// REST Client allows you to send HTTP request and view the response in Visual Studio Code directly.
// marketplace.visualstudio.com/items?itemName=humao.rest-client

http://
// API TO RETRIEVE HELP INFORMATION 
###

http://
// API TO RETRIEVE SCORE
###

http://
// API TO RETRIEVE USER LIST
###


